### ISSUE TITLE
Rename Repo 

### ISSUE THREAD

**Issue by leotovell** [freddycansic/OpenGL#3]
Mens, I have poor eyesight and slightly illiterate. WHat is openGL sir. Brain no understood so pls renam it to someting bettr for my brain pls.

**Comment by freddycansic** [comment]
I agree that the name is not very descriptive but I am struggling with coming up with better names. Any suggestions would be welcomed.

**Comment by leotovell** [comment]
OpenGL-3D-Object-Renderer-with-Object-translation-,-rotation-and-scaling-and-View-translation-,-rotation-and-scaling

**Comment by freddycansic** [comment]
This name is more descriptive however it does not roll off of the tongue like I would like it to.

**Comment by leotovell** [comment]
How dare you close this issue without a resolution. The customer is **ALWAYS** right.

Please rename the repo to: "OpenGL-3D-Object-Renderer-with-Object-translation-,-rotation-and-scaling-and-View-translation-,-rotation-and-scaling"

If you are unsure how to do so, please follow this [guide](https://docs.github.com/en/repositories/creating-and-managing-repositories/renaming-a-repository)
